server:
  port: 9999


spring:
  jackson:
    time-zone: Asia/Seoul
  data:
    mongodb:
      uri: mongodb+srv://S09P31B205:z5HxUpl4gB@ssafy.ngivl.mongodb.net/S09B31B205?authSource=admin
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/enjoytrip?serverTimezone=Asia/Seoul
    username: root
    password: ssafy
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create

# mongoDB

